<?php
/**
 * File for class KPMGStructIndataType
 * @package KPMG
 * @subpackage Structs
 * @author WsdlToPhp Team <contact@wsdltophp.com>
 * @version 20150429-01
 * @date 2018-07-24
 */
/**
 * This class stands for KPMGStructIndataType originally named IndataType
 * Documentation : Contains batch level request fields as well as a list of invoices.
 * Meta informations extracted from the WSDL
 * - from schema : {@link https://kpmg-uat.hostedtax.thomsonreuters.com/sabrix/services/taxcalculationservice/2011-09-01/taxcalculationservice?xsd=TaxCalculationService.xsd}
 * @package KPMG
 * @subpackage Structs
 * @author WsdlToPhp Team <contact@wsdltophp.com>
 * @version 20150429-01
 * @date 2018-07-24
 */
class KPMGStructIndataType extends KPMGWsdlClass
{
    /**
     * The COMPANY_ID
     * Meta informations extracted from the WSDL
     * - minOccurs : 0
     * - documentation : The internal Determination ID of the merchant.
     * @var long
     */
    public $COMPANY_ID;
    /**
     * The COMPANY_NAME
     * Meta informations extracted from the WSDL
     * - minOccurs : 0
     * - documentation : The name of the company running the transaction. ONESOURCE Indirect Tax Determination uses this element to apply the correct company-specific settings for the transaction.Required if EXTERNAL_COMPANY_ID is not populated.
     * - maxLength : 100
     * - minLength : 0
     * @var string
     */
    public $COMPANY_NAME;
    /**
     * The COMPANY_ROLE
     * Meta informations extracted from the WSDL
     * - minOccurs : 0
     * - documentation : The role the company plays in a given transaction: Buyer (B). Each role results in different transaction tax and reporting requirements.
     * - maxLength : 20
     * - minLength : 0
     * @var string
     */
    public $COMPANY_ROLE;
    /**
     * The EXTERNAL_COMPANY_ID
     * Meta informations extracted from the WSDL
     * - minOccurs : 0
     * - documentation : The unique identifier used by your business application to indicate which company to use in Determination. This identifier also distinguishes between different calling applications that may be used by your company. This element may be passed at the batch level or with each invoice, and is passed through to the Determination output and the audit tables.Required if COMPANY_NAME is not populated.
     * - maxLength : 100
     * - minLength : 0
     * @var string
     */
    public $EXTERNAL_COMPANY_ID;
    /**
     * The SCENARIO_ID
     * Meta informations extracted from the WSDL
     * - documentation : This is an internal ID generated by Determination for Workbench scenarios.
     * - minOccurs : 0
     * @var long
     */
    public $SCENARIO_ID;
    /**
     * The SCENARIO_NAME
     * Meta informations extracted from the WSDL
     * - minOccurs : 0
     * - documentation : This is the name of the Determination Workbench scenario.
     * - maxLength : 100
     * - minLength : 0
     * @var string
     */
    public $SCENARIO_NAME;
    /**
     * The XML_GROUP_NAME
     * Meta informations extracted from the WSDL
     * - minOccurs : 0
     * - documentation : The XML Group you want to use for the transaction. XML Groups determine those elements that Determination passes back to the calling application. If the XML group specified here is invalid (owned by the wrong company) for an invoice contained in the current XML transaction, the XML group specified for the company on that invoice is used instead. See the XML Output section of the Online Help for more information.
     * - maxLength : 30
     * - minLength : 1
     * @var string
     */
    public $XML_GROUP_NAME;
    /**
     * The XML_GROUP_OWNER
     * Meta informations extracted from the WSDL
     * - minOccurs : 0
     * - documentation : The company name associated with the XML group being used. This must be an ancestor of the submitting company or the company itself.Do not use slashes or characters in company names.
     * - maxLength : 100
     * - minLength : 1
     * @var string
     */
    public $XML_GROUP_OWNER;
    /**
     * The USERNAME
     * Meta informations extracted from the WSDL
     * - minOccurs : 0
     * - documentation : Database user name used to validate transaction submitter.Required if the CALC_AUTHENTICATION_REQUIRED Sabrix Config Parameter is set to Y and a custom authentication scheme has not been implemented.
     * - maxLength : 60
     * - minLength : 1
     * @var string
     */
    public $USERNAME;
    /**
     * The PASSWORD
     * Meta informations extracted from the WSDL
     * - minOccurs : 0
     * - documentation : Database user password used to validate the transaction submitter.Required if the CALC_AUTHENTICATION_REQUIRED Sabrix Config Parameter is set to Y and a custom authentication scheme has not been implemented.
     * - maxLength : 16
     * - minLength : 1
     * @var string
     */
    public $PASSWORD;
    /**
     * The HOST_SYSTEM
     * Meta informations extracted from the WSDL
     * - minOccurs : 0
     * - documentation : The name of the ERP instance sending the transaction.Note: Determination supports two audit keys to enable the lookup of audit records. The two combinations are as follows:HOST_SYSTEMCALLING_SYSTEM_NUMBERUNIQUE_INVOICE_NUMBERorMERCHANT_IDINVOICE_NUMINVOICE_DATEConfiguration parameters can modify which keys are used and in which order. See Sabrix Config and then contact Customer Support for more information.
     * - maxLength : 100
     * - minLength : 0
     * @var string
     */
    public $HOST_SYSTEM;
    /**
     * The HOST_REQUEST_INFO
     * Meta informations extracted from the WSDL
     * - minOccurs : 0
     * @var KPMGStructHostRequestInfoType
     */
    public $HOST_REQUEST_INFO;
    /**
     * The CALLING_SYSTEM_NUMBER
     * Meta informations extracted from the WSDL
     * - minOccurs : 0
     * - documentation : A pass-through element that contains a descriptor of the calling system sending the transaction.<bold>Note</bold>: ONESOURCE Indirect Tax Determination supports two audit keys to enable the lookup of audit records. The two combinations are as follows:HOST_SYSTEMCALLING_SYSTEM_NUMBERUNIQUE_INVOICE_NUMBERorMERCHANT_IDINVOICE_NUMINVOICE_DATEConfiguration parameters can modify which keys are used and in which order. See Sabrix Config and then contact Customer Support for more information.
     * - maxLength : 100
     * - minLength : 0
     * @var string
     */
    public $CALLING_SYSTEM_NUMBER;
    /**
     * The INVOICE
     * Meta informations extracted from the WSDL
     * - maxOccurs : unbounded
     * @var KPMGStructIndataInvoiceType
     */
    public $INVOICE;
    /**
     * The version
     * @var KPMGEnumVersionType
     */
    public $version;
    /**
     * Constructor method for IndataType
     * @see parent::__construct()
     * @param long $_cOMPANY_ID
     * @param string $_cOMPANY_NAME
     * @param string $_cOMPANY_ROLE
     * @param string $_eXTERNAL_COMPANY_ID
     * @param long $_sCENARIO_ID
     * @param string $_sCENARIO_NAME
     * @param string $_xML_GROUP_NAME
     * @param string $_xML_GROUP_OWNER
     * @param string $_uSERNAME
     * @param string $_pASSWORD
     * @param string $_hOST_SYSTEM
     * @param KPMGStructHostRequestInfoType $_hOST_REQUEST_INFO
     * @param string $_cALLING_SYSTEM_NUMBER
     * @param KPMGStructIndataInvoiceType $_iNVOICE
     * @param KPMGEnumVersionType $_version
     * @return KPMGStructIndataType
     */
    public function __construct($_cOMPANY_ID = NULL,$_cOMPANY_NAME = NULL,$_cOMPANY_ROLE = NULL,$_eXTERNAL_COMPANY_ID = NULL,$_sCENARIO_ID = NULL,$_sCENARIO_NAME = NULL,$_xML_GROUP_NAME = NULL,$_xML_GROUP_OWNER = NULL,$_uSERNAME = NULL,$_pASSWORD = NULL,$_hOST_SYSTEM = NULL,$_hOST_REQUEST_INFO = NULL,$_cALLING_SYSTEM_NUMBER = NULL,$_iNVOICE = NULL,$_version = NULL)
    {
        parent::__construct(array('COMPANY_ID'=>$_cOMPANY_ID,'COMPANY_NAME'=>$_cOMPANY_NAME,'COMPANY_ROLE'=>$_cOMPANY_ROLE,'EXTERNAL_COMPANY_ID'=>$_eXTERNAL_COMPANY_ID,'SCENARIO_ID'=>$_sCENARIO_ID,'SCENARIO_NAME'=>$_sCENARIO_NAME,'XML_GROUP_NAME'=>$_xML_GROUP_NAME,'XML_GROUP_OWNER'=>$_xML_GROUP_OWNER,'USERNAME'=>$_uSERNAME,'PASSWORD'=>$_pASSWORD,'HOST_SYSTEM'=>$_hOST_SYSTEM,'HOST_REQUEST_INFO'=>$_hOST_REQUEST_INFO,'CALLING_SYSTEM_NUMBER'=>$_cALLING_SYSTEM_NUMBER,'INVOICE'=>$_iNVOICE,'version'=>$_version),false);
    }
    /**
     * Get COMPANY_ID value
     * @return long|null
     */
    public function getCOMPANY_ID()
    {
        return $this->COMPANY_ID;
    }
    /**
     * Set COMPANY_ID value
     * @param long $_cOMPANY_ID the COMPANY_ID
     * @return long
     */
    public function setCOMPANY_ID($_cOMPANY_ID)
    {
        return ($this->COMPANY_ID = $_cOMPANY_ID);
    }
    /**
     * Get COMPANY_NAME value
     * @return string|null
     */
    public function getCOMPANY_NAME()
    {
        return $this->COMPANY_NAME;
    }
    /**
     * Set COMPANY_NAME value
     * @param string $_cOMPANY_NAME the COMPANY_NAME
     * @return string
     */
    public function setCOMPANY_NAME($_cOMPANY_NAME)
    {
        return ($this->COMPANY_NAME = $_cOMPANY_NAME);
    }
    /**
     * Get COMPANY_ROLE value
     * @return string|null
     */
    public function getCOMPANY_ROLE()
    {
        return $this->COMPANY_ROLE;
    }
    /**
     * Set COMPANY_ROLE value
     * @param string $_cOMPANY_ROLE the COMPANY_ROLE
     * @return string
     */
    public function setCOMPANY_ROLE($_cOMPANY_ROLE)
    {
        return ($this->COMPANY_ROLE = $_cOMPANY_ROLE);
    }
    /**
     * Get EXTERNAL_COMPANY_ID value
     * @return string|null
     */
    public function getEXTERNAL_COMPANY_ID()
    {
        return $this->EXTERNAL_COMPANY_ID;
    }
    /**
     * Set EXTERNAL_COMPANY_ID value
     * @param string $_eXTERNAL_COMPANY_ID the EXTERNAL_COMPANY_ID
     * @return string
     */
    public function setEXTERNAL_COMPANY_ID($_eXTERNAL_COMPANY_ID)
    {
        return ($this->EXTERNAL_COMPANY_ID = $_eXTERNAL_COMPANY_ID);
    }
    /**
     * Get SCENARIO_ID value
     * @return long|null
     */
    public function getSCENARIO_ID()
    {
        return $this->SCENARIO_ID;
    }
    /**
     * Set SCENARIO_ID value
     * @param long $_sCENARIO_ID the SCENARIO_ID
     * @return long
     */
    public function setSCENARIO_ID($_sCENARIO_ID)
    {
        return ($this->SCENARIO_ID = $_sCENARIO_ID);
    }
    /**
     * Get SCENARIO_NAME value
     * @return string|null
     */
    public function getSCENARIO_NAME()
    {
        return $this->SCENARIO_NAME;
    }
    /**
     * Set SCENARIO_NAME value
     * @param string $_sCENARIO_NAME the SCENARIO_NAME
     * @return string
     */
    public function setSCENARIO_NAME($_sCENARIO_NAME)
    {
        return ($this->SCENARIO_NAME = $_sCENARIO_NAME);
    }
    /**
     * Get XML_GROUP_NAME value
     * @return string|null
     */
    public function getXML_GROUP_NAME()
    {
        return $this->XML_GROUP_NAME;
    }
    /**
     * Set XML_GROUP_NAME value
     * @param string $_xML_GROUP_NAME the XML_GROUP_NAME
     * @return string
     */
    public function setXML_GROUP_NAME($_xML_GROUP_NAME)
    {
        return ($this->XML_GROUP_NAME = $_xML_GROUP_NAME);
    }
    /**
     * Get XML_GROUP_OWNER value
     * @return string|null
     */
    public function getXML_GROUP_OWNER()
    {
        return $this->XML_GROUP_OWNER;
    }
    /**
     * Set XML_GROUP_OWNER value
     * @param string $_xML_GROUP_OWNER the XML_GROUP_OWNER
     * @return string
     */
    public function setXML_GROUP_OWNER($_xML_GROUP_OWNER)
    {
        return ($this->XML_GROUP_OWNER = $_xML_GROUP_OWNER);
    }
    /**
     * Get USERNAME value
     * @return string|null
     */
    public function getUSERNAME()
    {
        return $this->USERNAME;
    }
    /**
     * Set USERNAME value
     * @param string $_uSERNAME the USERNAME
     * @return string
     */
    public function setUSERNAME($_uSERNAME)
    {
        return ($this->USERNAME = $_uSERNAME);
    }
    /**
     * Get PASSWORD value
     * @return string|null
     */
    public function getPASSWORD()
    {
        return $this->PASSWORD;
    }
    /**
     * Set PASSWORD value
     * @param string $_pASSWORD the PASSWORD
     * @return string
     */
    public function setPASSWORD($_pASSWORD)
    {
        return ($this->PASSWORD = $_pASSWORD);
    }
    /**
     * Get HOST_SYSTEM value
     * @return string|null
     */
    public function getHOST_SYSTEM()
    {
        return $this->HOST_SYSTEM;
    }
    /**
     * Set HOST_SYSTEM value
     * @param string $_hOST_SYSTEM the HOST_SYSTEM
     * @return string
     */
    public function setHOST_SYSTEM($_hOST_SYSTEM)
    {
        return ($this->HOST_SYSTEM = $_hOST_SYSTEM);
    }
    /**
     * Get HOST_REQUEST_INFO value
     * @return KPMGStructHostRequestInfoType|null
     */
    public function getHOST_REQUEST_INFO()
    {
        return $this->HOST_REQUEST_INFO;
    }
    /**
     * Set HOST_REQUEST_INFO value
     * @param KPMGStructHostRequestInfoType $_hOST_REQUEST_INFO the HOST_REQUEST_INFO
     * @return KPMGStructHostRequestInfoType
     */
    public function setHOST_REQUEST_INFO($_hOST_REQUEST_INFO)
    {
        return ($this->HOST_REQUEST_INFO = $_hOST_REQUEST_INFO);
    }
    /**
     * Get CALLING_SYSTEM_NUMBER value
     * @return string|null
     */
    public function getCALLING_SYSTEM_NUMBER()
    {
        return $this->CALLING_SYSTEM_NUMBER;
    }
    /**
     * Set CALLING_SYSTEM_NUMBER value
     * @param string $_cALLING_SYSTEM_NUMBER the CALLING_SYSTEM_NUMBER
     * @return string
     */
    public function setCALLING_SYSTEM_NUMBER($_cALLING_SYSTEM_NUMBER)
    {
        return ($this->CALLING_SYSTEM_NUMBER = $_cALLING_SYSTEM_NUMBER);
    }
    /**
     * Get INVOICE value
     * @return KPMGStructIndataInvoiceType|null
     */
    public function getINVOICE()
    {
        return $this->INVOICE;
    }
    /**
     * Set INVOICE value
     * @param KPMGStructIndataInvoiceType $_iNVOICE the INVOICE
     * @return KPMGStructIndataInvoiceType
     */
    public function setINVOICE($_iNVOICE)
    {
        return ($this->INVOICE = $_iNVOICE);
    }
    /**
     * Get version value
     * @return KPMGEnumVersionType|null
     */
    public function getVersion()
    {
        return $this->version;
    }
    /**
     * Set version value
     * @uses KPMGEnumVersionType::valueIsValid()
     * @param KPMGEnumVersionType $_version the version
     * @return KPMGEnumVersionType
     */
    public function setVersion($_version)
    {
        if(!KPMGEnumVersionType::valueIsValid($_version))
        {
            return false;
        }
        return ($this->version = $_version);
    }
    /**
     * Method called when an object has been exported with var_export() functions
     * It allows to return an object instantiated with the values
     * @see KPMGWsdlClass::__set_state()
     * @uses KPMGWsdlClass::__set_state()
     * @param array $_array the exported values
     * @return KPMGStructIndataType
     */
    public static function __set_state(array $_array,$_className = __CLASS__)
    {
        return parent::__set_state($_array,$_className);
    }
    /**
     * Method returning the class name
     * @return string __CLASS__
     */
    public function __toString()
    {
        return __CLASS__;
    }
}
